import { Boxes, CloudCog, Radar, Workflow } from 'lucide-react';

const capabilities = [
  { icon: Workflow, number: '01', title: 'Trusted software supply chains', text: 'CI/CD guardrails spanning code, dependencies, builds, and artifacts—with SAST, secret detection, SBOMs, provenance, signing, and risk-based promotion.', tags: ['SLSA', 'Cosign', 'Syft', 'Semgrep'] },
  { icon: CloudCog, number: '02', title: 'Identity-first cloud security', text: 'Hardened AWS foundations with least privilege, short-lived credentials, policy as code, encrypted workloads, posture monitoring, and auditable change.', tags: ['AWS IAM', 'OPA', 'Terraform', 'Security Hub'] },
  { icon: Boxes, number: '03', title: 'Secure platform engineering', text: 'Kubernetes paved roads with GitOps reconciliation, admission controls, workload isolation, runtime detection, and developer-friendly golden paths.', tags: ['EKS', 'Argo CD', 'Kyverno', 'Falco'] },
  { icon: Radar, number: '04', title: 'Detection & resilience', text: 'Telemetry that connects engineering and security: OpenTelemetry signals, actionable SLOs, threat detection, incident context, and recovery-ready operations.', tags: ['OpenTelemetry', 'Prometheus', 'Grafana', 'SLOs'] },
];

export default function ProfessionalFocus() {
  return <section id="capabilities" className="section-shell bg-slate-50 dark:bg-slate-900/40"><div className="mx-auto max-w-7xl px-5 lg:px-10"><p className="section-kicker">02 / Capabilities</p><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-title max-w-2xl">Security embedded across the <span className="gradient-text">delivery system.</span></h2><p className="max-w-sm text-slate-600 dark:text-slate-400">Outcome-led engineering across code, cloud, clusters, and runtime.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 dark:border-white/10 dark:bg-white/10 md:grid-cols-2">{capabilities.map(({icon: Icon, number, title, text, tags}) => <article className="capability-card" key={title}><div className="flex items-center justify-between"><Icon className="text-emerald-500" size={28}/><span className="font-mono text-xs text-slate-400">{number}</span></div><h3 className="mt-8 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-4 leading-7 text-slate-600 dark:text-slate-400">{text}</p><div className="mt-7 flex flex-wrap gap-2">{tags.map(tag => <span className="tech-pill" key={tag}>{tag}</span>)}</div></article>)}</div></div></section>;
}
